FROM nginx:alpine

RUN rm -rf /usr/share/nginx/html/*

COPY ./default.conf.template /etc/nginx/templates/default.conf.template

# Copy static files
COPY ./dist/ /usr/share/nginx/html/

# Expose port 80
EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]