FROM nginx:alpine

# Install envsubst
RUN apk add --no-cache gettext

RUN rm -rf /usr/share/nginx/html/*

COPY ./default.conf.template /etc/nginx/templates/default.conf.template

# ENV API_URL=$API_URL

# # Copy your Nginx configuration
# RUN envsubst '${API_URL}' < /etc/nginx/templates/default.conf.template > /etc/nginx/conf.d/default.conf

# Copy static files
COPY ./dist/ /usr/share/nginx/html/

# Expose port 80
EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]