FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build

WORKDIR /src
COPY ["GandalfApi/GandalfApi.csproj", "GandalfApi/"]
RUN dotnet restore "GandalfApi/GandalfApi.csproj"
COPY . .
WORKDIR "/src/GandalfApi"
RUN dotnet build "GandalfApi.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "GandalfApi.csproj" -c Release -o /app/publish

FROM mcr.microsoft.com/dotnet/aspnet:8.0.15-bookworm-slim AS final
WORKDIR /app

COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "GandalfApi.dll"]